Adding Miron as a maintainer (#36)
* Adding Miron as a maintainer

* bump build number

* MNT: Re-rendered with conda-build 24.3.0, conda-smithy 3.34.1, and conda-forge-pinning 2024.04.05.11.09.57

* Fixing python-control numpy version clash for older Pythons

* try other syntax for range

* try always less than the recent

* try higher minimum numpy for this control package issue

* more windows 3.9 issues

* didn't work

* more attempts to fix old python+control package issues

* another go

* another go

* another go

* another go

* Trying to fix win3.9 error TypeError: entry_points() got an unexpected keyword argument 'group'

* try and limit networkx version for win py39

* fixes

---------

Co-authored-by: conda-forge-webservices[bot] <91080706+conda-forge-webservices[bot]@users.noreply.github.com>